 server:
   port: 9010    

 eureka:
   client:
      service-url:
        defaultZone: http://localhost:8761/eureka
   instance:
       prefer-ip-address: true
             
 spring:
   application:
     name: GATEWAY-SERVICE
   cloud:
     gateway:
       routes:
       - id: FirstService
         uri: lb://first-service
         predicates:
         - Path=/first/**
       - id: SecondService
         uri: http://localhost:9007/welcome/
         predicates:
         - Path=/second/** 
        
       
                
           
